#############################################
# Stalwart Mail Server Configuration File   
#############################################

[server.listener."smtp"]
bind = ["[::]:25"]
protocol = "smtp"

[server.listener."submission"]
bind = ["[::]:587"]
protocol = "smtp"

[server.listener."submissions"]
bind = ["[::]:465"]
protocol = "smtp"
tls.implicit = true

[server.listener."imap"]
bind = ["[::]:143"]
protocol = "imap"

[server.listener."imaptls"]
bind = ["[::]:993"]
protocol = "imap"
tls.implicit = true

[server.listener.pop3]
bind = "[::]:110"
protocol = "pop3"

[server.listener.pop3s]
bind = "[::]:995"
protocol = "pop3"
tls.implicit = true

[server.listener."sieve"]
bind = ["[::]:4190"]
protocol = "managesieve"

[server.listener."https"]
protocol = "http"
bind = ["[::]:443"]
tls.implicit = true

# Uncomment after testing
#[storage]
#data = "rocksdb"
#fts = "rocksdb"
#blob = "rocksdb"
#lookup = "rocksdb"
#directory = "internal"
#
#[store."rocksdb"]
#type = "rocksdb"
#path = "%{env:STALWART_PATH}%/data"
#compression = "lz4"
#
#[directory."internal"]
#type = "internal"
#store = "rocksdb"
# Uncomment after testing

# Delete after testing
[storage]
data = "tikv"
fts = "tikv"
blob = "tikv"
lookup = "tikv"
directory = "internal"

[store."tikv"]
type = "tikv"
pd-endpoints = ["127.0.0.1:2379"]

[directory."internal"]
type = "internal"
store = "tikv"
# Delete after testing

[tracer."stdout"]
type = "stdout"
level = "trace" # switch back to info after debugging
ansi = false
enable = true

#[server.run-as]
#user = "stalwart-mail"
#group = "stalwart-mail"

[authentication.fallback-admin]
user = "admin"
secret = "%{env:ADMIN_SECRET}%"
